site_name: "Defensoria Pública do Distrito Federal"
repo_url: https://github.com/interacao-humano-computador/2024.2-Grupo02/
repo_name: "2024.2-Grupo02"


plugins:
    - search
    - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
  language: pt-BR

extra_css:
  - assets/css/extra.css

nav:
  - Home: index.md
  - Planejamento:
    - Cronograma: Planejamento/cronograma.md
    - Sites avaliados: Planejamento/sites_avaliados.md
    - Site escolhido: Planejamento/site_escolhido.md
    - Processo de Design: Planejamento/processo_design.md
    - Ferramentas: Planejamento/ferramentas.md
    - HeatMap: Planejamento/heat_map.md
    - Aspectos Éticos: Analise/aspectoseticos.md
    - Atas de reunião:
      - Ata 1° reunião - 02/11/2024: Atas/ata_reunião1.md
      - Ata 2° reunião - 09/11/2024: Atas/ata_reunião2.md
      - Ata 3° reunião - 10/11/2024: Atas/ata_reunião3.md
  - Apresentações:
    - Apresentação etapa 1: Apresentacoes/apresentacao1.md
    - Apresentação etapa 2: Apresentacoes/apresentacao2.md
    - Apresentação etapa 3: Apresentacoes/apresentacao3.md
    - Apresentação etapa 5: Apresentacoes/apresentacao5.md
    - Apresentação etapa 6: Apresentacoes/apresentacao6.md
    - Apresentação etapa 7: Apresentacoes/apresentacao7.md
  - Análise de Requisitos:
    - Perfil de Usuário: Analise/perfilUsuario.md
    - Personas: Analise/personas.md
    - Cenários: Analise/cenarios.md
    - Analise de Tarefas: Analise/AnaliseTarefas.md
    - Características da Plataforma: Analise/caracteristicas.md
    - Guia de Estilo: Analise/guiaDeEstilo.md
    - Metas de Usabilidade: Analise/metasdeusabilidade.md
    - Principios Gerais: Analise/PrincipiosGerais.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
        - Análise de Tarefas:
            - Planejamento da avaliação da Análise de Tarefas: Desenvolvimento/analiseDeTarefas.md
            - Planejamento do Relato dos Resultados da Análise de Tarefas: Desenvolvimento/planejamentoRelatoAnaliseTarefas.md
            - Resultado do Relato da Análise de Tarefas: Desenvolvimento/resultado_analiseTarefas.md
        - Storyboard:
            - Storyboards: Desenvolvimento/storyboards.md
            - Planejamento da avaliação do Storyboard: Desenvolvimento/planejamento_storyboard.md
            - Planejamento do Relato dos Resultados do Storyboard: Desenvolvimento/Planejamento_relatodoStoryborad.md
            - Resultado do Relato do Storyboard: Desenvolvimento/resultado_Storyboard.md
    - Nível 2:
        - Protótipo de Papel:
            - Protótipos de Papel: Desenvolvimento/ProtiposdePapel.md
            - Planejamento do Protótipo de Papel: Desenvolvimento/Planejamento_prototipoPapel.md
            - Planejamento do Relato dos Resultados do Protótipo de Papel: Desenvolvimento/Planejamento_resultados_prototipoPapel.md
            - Resultado do Relato do Protótipo de Papel: Desenvolvimento/Relato_prototipoPapel.md
    - Nível 3:
        - Protótipo de Alta Fidelidade:
            - Protótipos de Alta Fidelidade: Desenvolvimento/PrototipoAlta.md
            - Planejamento do Protótipo de Alta Fidelidade: Desenvolvimento/PlanejamentoAltaFidelidade.md
            - Planejamento do Relato dos Resultados do Protótipo de Alta Fidelidade: Desenvolvimento/PlaneRelatoAltaFidelidade.md
            - Resultado do Relato do Protótipo de Alta Fidelidade: Desenvolvimento/Resultado_prototipoAltaFidelidade.md
  - Inspeção:
    - Inspeção 1° etapa: Inspecao/inspecao_etapa1.md
    - Inspeção 2º etapa: Inspecao/inspecao_etapa2.md
    - Inspeção 3º etapa: Inspecao/inspecao_etapa3.md
    - Inspeção 4ª etapa: Inspecao/inspecao_etapa4.md 
    - Inspeção 5º etapa: Inspecao/inspecao_etapa5.md
    - Inspeção 6º etapa: Inspecao/inspecao_etapa6.md
    - Inspeção 7º etapa: Inspecao/inspecao_etapa7.md
    
  - Verificação:
    - Verificação Análise de Tarefas:
          - Planejamento da Verificação Análise de Tarefas: Verificacao/plan_verif_analisetarefas.md
          - Resultado Verificação Análise de Tarefas: Verificacao/verificacao_analiseTarefas.md
    - Verificação Cenários:
          - Planejamento da Verificação Cenários: Verificacao/plan_verif_cenario.md
          - Resultado Verificação Cenários: Verificacao/verificacao_cenarios.md
    - Veificação Personas:
          - Planejamento da Verificação Personas: Verificacao/plan_verif_personas.md
          - Resultado Verificação Personas: Verificacao/verificacao_personas.md
    - Verificação Elenco de personas:
          - Planejamento da Verificação Elenco de personas: Verificacao/plan_verif_elencopersonas.md
          - Resultado Verificação Elenco de Personas: Verificacao/verificacao_ElencodePersonas.md
    - Verificação Framework DECIDE:
          - Planejamento da Verificação Framework DECIDE: Verificacao/plan_verif_frameworkDECIDE.md
          - Resultado Verificação Framework DECIDE: Verificacao/verificacao_frameworkDECIDE.md
    - Verificação Planejamento do Resultado e Resultado:
          - Planejamento da Verificação Planejamento do Resultado e Resultado: Verificacao/plan_verif_planejresult.md
          - Resultado Verificação Planejamento do Resultado e Resultado: Verificacao/plan_verif_Resultado.md  
    - Verificação árvore de Tarefas Concorrentes:
          - Planejamento da Verificação Árvore de Tarefas Concorrentes: Verificacao/plan_verif_arvoreTarefas.md
          - Resultado Verificação Árvore de Tarefas Concorrentes: Verificacao/verificacao_arvoreTarefas.md



  - Guia de Contribuição:
    - Politicas: Contribuição/Politicas.md
    - Como contribuir?: Contribuição/Tutorial.md
    - Práticas:
      - Políticas de Branchs: Contribuição/Politicas/Branch.md
      - Políticas de Commit: Contribuição/Politicas/Commit.md
      - Políticas de Pull Request: Contribuição/Politicas/PullRequest.md

# =============================================
# Tutorial para adicionar novas páginas
# =============================================
# 
# 1. Crie um arquivo .md dentro do diretório "docs".
#    Por exemplo, você pode criar "docs/sobre.md" para uma página Sobre.
#
# 2. Para adicionar esta página à navegação do site:
#    - Adicione uma nova entrada em "nav" como no exemplo abaixo.
#
#      nav:
#        - Home: index.md
#        - Sobre: sobre.md
#
#    Isso fará com que a página "sobre.md" apareça no menu de navegação 
#    com o nome "Sobre".
#
# 3. Organizando em seções:
#    - Para criar uma seção com várias páginas, use uma lista.
#    - Exemplo:
#
#      nav:
#        - Home: index.md
#        - Projeto:
#            - Visão Geral: projeto/visao_geral.md
#            - Objetivos: projeto/objetivos.md
#
#    Nesse caso, as páginas "visao_geral.md" e "objetivos.md" estarão
#    em uma seção chamada "Projeto" no menu de navegação.
#
# =============================================

